name: Shell Commands


on: [push]


jcbs:
  run-shell-command: 
  runs-on: ubuntu-latest
  steps: 
    - name: echo a string
      run: echo "Hello World"
    - name: multiline script
      run: |
        node -v
        npm -v
